### Practice Questions for Numpy

In [22]:
import numpy as np

In [23]:
# Question 1
# Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[4, 5, 6],
              [7, 8, 9]])

vertical_stack = np.vstack((A, B))

horizontal_stack = np.hstack((A, B))

print(f"A: ")
print(A)
print("\nB:")
print(B)
print("\nStacked Vertically:")
print(vertical_stack)
print("\nStacked Horizontally:")
print(horizontal_stack)

A: 
[[1 2 3]
 [4 5 6]]

B:
[[4 5 6]
 [7 8 9]]

Stacked Vertically:
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]

Stacked Horizontally:
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [24]:
# Question 2
# Find common elements between A and B. [Hint : Intersection of two sets]

set_A = set(A.flatten())
set_B = set(B.flatten())

common_elements = set_A.intersection(set_B)

print("Common elements between A and B:", common_elements)

Common elements between A and B: {4, 5, 6}


In [25]:
# Question 3
# Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

lower_bound = 5
upper_bound = 10

mask = (A >= lower_bound) & (A <= upper_bound)

elements_within_range = A[mask]

print(f"Elements within the range [{lower_bound}, {upper_bound}]: {elements_within_range}")

Elements within the range [5, 10]: [5 6]


In [26]:
# Question 4
# Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[mask]

print("Filtered rows:")
print(filtered_rows)

Filtered rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Practice Questions for Pandas

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [29]:
# Question 1
# From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

filtered_data = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_data)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [30]:
# Question 2
# Replace missing values in Min.Price and Max.Price columns with their respective mean.

min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [31]:
# Question 3
# How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered_rows = df[df.sum(axis=1) > 100]
print(filtered_rows)

     0   1   2   3
2   14  24  37  39
3   30  21  23  29
4   39  37  31  38
5   39  38  10  24
7   39  39  18  14
8   30  36  33  37
10  12  14  38  37
11  28  38  25  30
12  11  34  29  34
